name: CI Checks
on:
  push:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        compiler:
          - gcc
          - clang
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install nasm
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install nasm
      - name: Run tests
        run: ./pleasew test -e e2e --profile ${{ matrix.compiler }} --log_file plz-out/log/test.log
      - name: Run e2e test
        run: ./pleasew test -i e2e --profile ${{ matrix.compiler }} --log_file plz-out/log/e2e.log
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            plz-out/log
      strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu-latest
            - macos-latest
          compiler:
            - gcc
            - clang